// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"
)

const deleteHistoryEntry = `-- name: DeleteHistoryEntry :exec
DELETE FROM history
WHERE id = ?
`

func (q *Queries) DeleteHistoryEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryEntry, id)
	return err
}

const getRecentHistory = `-- name: GetRecentHistory :many
SELECT id, "query", provider_id, provider_tag, timestamp FROM history
ORDER BY timestamp ASC 
LIMIT ?
`

func (q *Queries) GetRecentHistory(ctx context.Context, limit int64) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, getRecentHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Query,
			&i.ProviderID,
			&i.ProviderTag,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHistoryEntry = `-- name: InsertHistoryEntry :exec
INSERT INTO history (
  query,
  provider_id,
  provider_tag
) VALUES (?, ?, ?)
`

type InsertHistoryEntryParams struct {
	Query       string `db:"query" json:"query"`
	ProviderID  int64  `db:"provider_id" json:"provider_id"`
	ProviderTag string `db:"provider_tag" json:"provider_tag"`
}

func (q *Queries) InsertHistoryEntry(ctx context.Context, arg InsertHistoryEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistoryEntry, arg.Query, arg.ProviderID, arg.ProviderTag)
	return err
}

const listHistory = `-- name: ListHistory :many
SELECT id, "query", provider_id, provider_tag, timestamp FROM history
`

func (q *Queries) ListHistory(ctx context.Context) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Query,
			&i.ProviderID,
			&i.ProviderTag,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
