// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type History struct {
	ID          int64     `db:"id" json:"id"`
	Query       string    `db:"query" json:"query"`
	ProviderID  int64     `db:"provider_id" json:"provider_id"`
	ProviderTag string    `db:"provider_tag" json:"provider_tag"`
	Timestamp   time.Time `db:"timestamp" json:"timestamp"`
}

type SearchProvider struct {
	ID          int64  `db:"id" json:"id"`
	Category    string `db:"category" json:"category"`
	Domain      string `db:"domain" json:"domain"`
	Rank        int64  `db:"rank" json:"rank"`
	SiteName    string `db:"site_name" json:"site_name"`
	Subcategory string `db:"subcategory" json:"subcategory"`
	Tag         string `db:"tag" json:"tag"`
	Url         string `db:"url" json:"url"`
}

type Session struct {
	ID        int64     `db:"id" json:"id"`
	Alias     string    `db:"alias" json:"alias"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Shortcut struct {
	ID        int64     `db:"id" json:"id"`
	Alias     string    `db:"alias" json:"alias"`
	Url       string    `db:"url" json:"url"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
