// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package sqlc

import (
	"context"
)

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM search_providers WHERE id = ?
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, id)
	return err
}

const getProviderByTag = `-- name: GetProviderByTag :one
SELECT id, category, domain, rank, site_name, subcategory, tag, url FROM search_providers WHERE tag = ?
`

func (q *Queries) GetProviderByTag(ctx context.Context, tag string) (SearchProvider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByTag, tag)
	var i SearchProvider
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Domain,
		&i.Rank,
		&i.SiteName,
		&i.Subcategory,
		&i.Tag,
		&i.Url,
	)
	return i, err
}

const insertProvider = `-- name: InsertProvider :exec
INSERT INTO search_providers (
    tag, 
    url, 
    category, 
    domain, 
    rank, 
    site_name, 
    subcategory
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertProviderParams struct {
	Tag         string `db:"tag" json:"tag"`
	Url         string `db:"url" json:"url"`
	Category    string `db:"category" json:"category"`
	Domain      string `db:"domain" json:"domain"`
	Rank        int64  `db:"rank" json:"rank"`
	SiteName    string `db:"site_name" json:"site_name"`
	Subcategory string `db:"subcategory" json:"subcategory"`
}

func (q *Queries) InsertProvider(ctx context.Context, arg InsertProviderParams) error {
	_, err := q.db.ExecContext(ctx, insertProvider,
		arg.Tag,
		arg.Url,
		arg.Category,
		arg.Domain,
		arg.Rank,
		arg.SiteName,
		arg.Subcategory,
	)
	return err
}

const listProviders = `-- name: ListProviders :many
SELECT id, category, domain, rank, site_name, subcategory, tag, url FROM search_providers ORDER BY rank DESC
`

func (q *Queries) ListProviders(ctx context.Context) ([]SearchProvider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProvider{}
	for rows.Next() {
		var i SearchProvider
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Domain,
			&i.Rank,
			&i.SiteName,
			&i.Subcategory,
			&i.Tag,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
