// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_urls.sql

package sqlc

import (
	"context"
)

const addSessionUrl = `-- name: AddSessionUrl :one
INSERT INTO session_urls (session_id, url) VALUES (?, ?) RETURNING id, session_id, url, created_at
`

type AddSessionUrlParams struct {
	SessionID int64  `db:"session_id" json:"session_id"`
	Url       string `db:"url" json:"url"`
}

func (q *Queries) AddSessionUrl(ctx context.Context, arg AddSessionUrlParams) (SessionUrl, error) {
	row := q.db.QueryRowContext(ctx, addSessionUrl, arg.SessionID, arg.Url)
	var i SessionUrl
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionUrls = `-- name: DeleteSessionUrls :exec
DELETE FROM session_urls WHERE session_id = ?
`

func (q *Queries) DeleteSessionUrls(ctx context.Context, sessionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionUrls, sessionID)
	return err
}

const listSessionUrls = `-- name: ListSessionUrls :many
SELECT id, session_id, url, created_at FROM session_urls WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListSessionUrls(ctx context.Context, sessionID int64) ([]SessionUrl, error) {
	rows, err := q.db.QueryContext(ctx, listSessionUrls, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionUrl{}
	for rows.Next() {
		var i SessionUrl
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
