// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionByAlias = `-- name: DeleteSessionByAlias :exec
DELETE FROM sessions
WHERE alias = ?
`

func (q *Queries) DeleteSessionByAlias(ctx context.Context, alias string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByAlias, alias)
	return err
}

const getSessionByAlias = `-- name: GetSessionByAlias :one
SELECT id, alias, created_at FROM sessions
WHERE alias = ?
`

func (q *Queries) GetSessionByAlias(ctx context.Context, alias string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByAlias, alias)
	var i Session
	err := row.Scan(&i.ID, &i.Alias, &i.CreatedAt)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
  alias
) VALUES (?)
RETURNING id, alias, created_at
`

func (q *Queries) InsertSession(ctx context.Context, alias string) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession, alias)
	var i Session
	err := row.Scan(&i.ID, &i.Alias, &i.CreatedAt)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, alias, created_at FROM sessions
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(&i.ID, &i.Alias, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET alias = ?
WHERE id = ?
RETURNING id, alias, created_at
`

type UpdateSessionParams struct {
	Alias string `db:"alias" json:"alias"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession, arg.Alias, arg.ID)
	var i Session
	err := row.Scan(&i.ID, &i.Alias, &i.CreatedAt)
	return i, err
}
