// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shortcuts.sql

package sqlc

import (
	"context"
)

const deleteShortcut = `-- name: DeleteShortcut :exec
DELETE FROM shortcuts
WHERE id = ?
`

func (q *Queries) DeleteShortcut(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteShortcut, id)
	return err
}

const deleteShortcutFromAlias = `-- name: DeleteShortcutFromAlias :exec
DELETE FROM shortcuts
WHERE alias = ?
`

func (q *Queries) DeleteShortcutFromAlias(ctx context.Context, alias string) error {
	_, err := q.db.ExecContext(ctx, deleteShortcutFromAlias, alias)
	return err
}

const getShortcutByAlias = `-- name: GetShortcutByAlias :one
SELECT id, alias, url, created_at FROM shortcuts
WHERE alias = ?
`

func (q *Queries) GetShortcutByAlias(ctx context.Context, alias string) (Shortcut, error) {
	row := q.db.QueryRowContext(ctx, getShortcutByAlias, alias)
	var i Shortcut
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const insertShortcut = `-- name: InsertShortcut :one
INSERT INTO shortcuts (
  alias, url
) VALUES (?, ?)
RETURNING id, alias, url, created_at
`

type InsertShortcutParams struct {
	Alias string `db:"alias" json:"alias"`
	Url   string `db:"url" json:"url"`
}

func (q *Queries) InsertShortcut(ctx context.Context, arg InsertShortcutParams) (Shortcut, error) {
	row := q.db.QueryRowContext(ctx, insertShortcut, arg.Alias, arg.Url)
	var i Shortcut
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const listShortcuts = `-- name: ListShortcuts :many
SELECT id, alias, url, created_at FROM shortcuts
`

func (q *Queries) ListShortcuts(ctx context.Context) ([]Shortcut, error) {
	rows, err := q.db.QueryContext(ctx, listShortcuts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shortcut{}
	for rows.Next() {
		var i Shortcut
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
